project 'Assignment2_insPhoto.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Assignment2_insPhoto' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Assignment2_insPhoto
pod 'DynamicColor', '~> 4.0'
  target 'Assignment2_insPhotoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Assignment2_insPhotoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
